INSERT INTO houses (
  title,
  slug,
  village_name,
  price,
  area_house,
  distance_mkad,
  floors,
  plot_area,
  image_path,
  short_description,
  full_description,
  is_active
)
VALUES
  (
    'Дом в Барвихе',
    'dom-v-barvihe',
    'Барвиха Luxury Village',
    320000000,
    620,
    9,
    2,
    18.00,
    '/media/images/ex1.png',
    'Современный дом с продуманной планировкой и приватным участком.',
    'Просторная резиденция с дизайнерской отделкой, зоной отдыха и удобной транспортной доступностью.',
    1
  ),
  (
    'Участок в Раздорах',
    'uchastok-v-razdorah',
    'Раздоры',
    110000000,
    0,
    12,
    0,
    22.00,
    '/media/images/ex2.png',
    'Участок в тихой локации с перспективой индивидуальной застройки.',
    'Лот для строительства резиденции с удобным подъездом и развитой инфраструктурой района.',
    1
  ),
  (
    'Резиденция в Жуковке',
    'rezidenciya-v-zhukovke',
    'Жуковка',
    450000000,
    780,
    14,
    3,
    24.00,
    '/media/images/ex3.jpg',
    'Премиальная резиденция в закрытом поселке.',
    'Трехэтажный дом с просторной гостевой зоной, кабинетом и террасой с видом на участок.',
    1
  ),
  (
    'Дом у леса',
    'dom-u-lesa',
    'Раздоры',
    270000000,
    510,
    11,
    2,
    16.50,
    '/media/images/ex4.jpg',
    'Дом с панорамным остеклением рядом с лесной зоной.',
    'Сбалансированный вариант для постоянного проживания: современная архитектура и приватный двор.',
    1
  ),
  (
    'Коттедж в Барвихе',
    'kottedzh-v-barvihe',
    'Барвиха Luxury Village',
    365000000,
    690,
    8,
    2,
    20.00,
    '/media/images/ex5.jpg',
    'Коттедж с высоким уровнем готовности и участком правильной формы.',
    'Дом в классической современной стилистике с функциональной планировкой для большой семьи.',
    1
  )
ON DUPLICATE KEY UPDATE
  village_name = VALUES(village_name),
  price = VALUES(price),
  area_house = VALUES(area_house),
  distance_mkad = VALUES(distance_mkad),
  floors = VALUES(floors),
  plot_area = VALUES(plot_area),
  image_path = VALUES(image_path),
  short_description = VALUES(short_description),
  full_description = VALUES(full_description),
  is_active = VALUES(is_active);
